In [12]:
#importing the necessay dependancies
import random
random.seed(0)
import numpy as np
np.random.seed(0)
import matplotlib.pyplot as plt
import tensorflow as tf
tf.random.set_seed(0)
from tensorflow.keras import models, layers
from tensorflow.keras.preprocessing.image import  ImageDataGenerator
import splitfolders
from IPython.display import HTML

In [13]:
#Defining the parameters
Image_size = 256
Channels = 3
Epochs = 15


In [18]:
train_datagenerator = ImageDataGenerator(
    rescale=1.0/255,            # Normalize pixel values
    rotation_range=20,          # Rotate images up to 20 degrees
    width_shift_range=0.2,      # Horizontal shift
    height_shift_range=0.2,     # Vertical shift
    shear_range=0.2,            # Shear transformation
    zoom_range=0.2,             # Zoom in/out
    horizontal_flip=True        # Flip horizontally
)

train_generator = train_datagenerator.flow_from_directory(
    r"D:\Projects\Farm_intel\dataset\train",
    target_size=(Image_size, Image_size),
    batch_size=32,
    class_mode='sparse'
)

Found 33836 images belonging to 26 classes.


In [19]:
test_datagenerator = ImageDataGenerator(
    rescale=1.0/255,            # Normalize pixel values
    rotation_range=20,          # Rotate images up to 20 degrees
    width_shift_range=0.2,      # Horizontal shift
    height_shift_range=0.2,     # Vertical shift
    shear_range=0.2,            # Shear transformation
    zoom_range=0.2,             # Zoom in/out
    horizontal_flip=True        # Flip horizontally
)

test_generator = test_datagenerator.flow_from_directory(
    r"D:\Projects\Farm_intel\dataset\test",
    target_size=(Image_size, Image_size),
    batch_size=32,
    class_mode='sparse'
)

Found 9694 images belonging to 26 classes.


In [20]:
val_datagenerator = ImageDataGenerator(
    rescale=1.0/255,            # Normalize pixel values
    rotation_range=20,          # Rotate images up to 20 degrees
    width_shift_range=0.2,      # Horizontal shift
    height_shift_range=0.2,     # Vertical shift
    shear_range=0.2,            # Shear transformation
    zoom_range=0.2,             # Zoom in/out
    horizontal_flip=True        # Flip horizontally
)

val_generator = val_datagenerator.flow_from_directory(
    r"D:\Projects\Farm_intel\dataset\val",
    target_size=(Image_size, Image_size),
    batch_size=32,
    class_mode='sparse'
)

Found 4822 images belonging to 26 classes.


In [24]:
for image_batch, label_batch in train_generator:
    print(image_batch[0])
    #print(label_batch.shape)
    

[[[0.8078432  0.7686275  0.7725491 ]
  [0.8078432  0.7686275  0.7725491 ]
  [0.8078432  0.7686275  0.7725491 ]
  ...
  [0.8256854  0.7864697  0.79039127]
  [0.8657983  0.8265826  0.8305042 ]
  [0.8556174  0.8164017  0.8203233 ]]

 [[0.8078432  0.7686275  0.7725491 ]
  [0.8078432  0.7686275  0.7725491 ]
  [0.8078432  0.7686275  0.7725491 ]
  ...
  [0.759063   0.7198473  0.7237689 ]
  [0.73548675 0.69627106 0.70019263]
  [0.8447404  0.8055247  0.8094463 ]]

 [[0.8001195  0.76090384 0.7648254 ]
  [0.8033472  0.7641315  0.76805305]
  [0.80657476 0.7673591  0.77128065]
  ...
  [0.78736925 0.74815357 0.75207514]
  [0.74310005 0.7038843  0.7078059 ]
  [0.7995283  0.7603126  0.7642342 ]]

 ...

 [[0.8235295  0.77647066 0.77647066]
  [0.8235295  0.77647066 0.77647066]
  [0.8235295  0.77647066 0.77647066]
  ...
  [0.69305456 0.6381526  0.63423103]
  [0.7296344  0.67473245 0.6708109 ]
  [0.76621425 0.7113123  0.7073907 ]]

 [[0.8235295  0.77647066 0.77647066]
  [0.8235295  0.77647066 0.77647066]


KeyboardInterrupt: 